### ISSUE TITLE
Namespace in ressources is incorrect

### ISSUE THREAD

**Issue by maximehuran** [PayboxByVerifone/Magento2#13]
Exemple in file : 
`paybox/epayment/Model/Resource/Payment/Threetime.php`

Namespace is : 
`namespace Paybox\Epayment\Model\Payment;`

Instead of : 
`namespace Paybox\Epayment\Model\Resource\Payment;`

This problem generate warning during composer install.

**Comment by bm-services** [comment]
Hi,
we removed those files in the new 1.0.8 release.

Regards,
BM Services
