### ISSUE TITLE
Add support for php 7.1

### ISSUE THREAD

**Issue by AlexPernot** [PayboxByVerifone/Magento2#17]
Hello,

With Magento 2.2, PHP 7.1 is now supported, which is great since we can finally use our distros' official packages. Unfortunately, this module is the last one blocking the upgrade, since its composer.json only supports php ~7.0.0.

Could you review the code and up the php version requirement ? Thanks!

**Comment by bm-services** [comment]
Hi,
we have tested the module on Magento 2.2 and PHP 7.1 and a new version has been released allowing the install.

We now presume the module is compatible with all PHP 7 versions and Magento 2 versions to not limit the use of the module to early PHP or Magento new version testers.

Regards.

**Comment by bm-services** [comment]
Fixed in 1.0.9 version : https://github.com/PayboxByVerifone/Magento2/releases/tag/v1.0.9
