### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicolallias** [PayboxByVerifone/Magento2#3]
Bonjour à tous,

**Premier point: dossier pour installer via composer.**
A propos de l'installation (via Composer, sur [la page du projet](https://github.com/PayboxByVerifone/Magento2) ), il y a une erreur :

> Exécuter la commande suivante pour la récupération des fichiers du module dans le dossier `<your Magento install dir>`/vendor (vous aurez besoin de vos identifiants Magento2) :
> composer` require paybox/epayment

Il faut en fait se placer directement dans le dossier racine de Magento  `<your Magento install dir>`, sous peine d'avoir le message suivant (avant même de demander les clés privées/publiques) :

> Your requirements could not be resolved to an installable set of packages.
> Problem 1
> - paybox/epayment 1.0.5 requires magento/framework ~100.0.4|~100.1.0 -> no matching package found.
> [...]
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> Installation failed, deleting ./composer.json.

**Deuxième point : les identifiants pour composer.**
Je connais mal composer, votre documentation m'a donné à penser que les identifiants requis pour composer étaient ceux du site, ou l'id du compte... il s'agit en fait des clés ([doc officielle pour les récupérer](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html)) ; ce n'est pas votre faute, mais ça m'a fait perdre du temps.
- Username: clé publique
- Password: clé privée

**Troisième point: Problème de configuration.**
J'ai installé le dernier magento stable du moment (2.1.5)

> Using version ^1.0 for paybox/epayment
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Failed to decode response: zlib_decode(): data error
< Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
> Installation failed, reverting ./composer.json to its original content.
>  [Composer\Downloader\TransportException]
  Your configuration does not allow connection to http://packagist.org. See https://getco
  mposer.org/doc/06-config.md#secure-http for details.
> require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

Extrait de mon composer.json:
> "repositories": [
>         {
>             "type": "composer",
>             "url": "https://repo.magento.com/"
>         }
>     ],

Grâce à une manip(  `composer config --global repositories.packagist.allow_ssl_downgrade false` [source](https://github.com/composer/composer/issues/4121)), l'installation a réussi, avec des avertissements :
> Failed to decode response: zlib_decode(): data error
> Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
> Your configuration does not allow connection to http://packagist.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.
> http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
> Using version ^1.0 for paybox/epayment
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   `-` Installing paybox/epayment (1.0.5)
>     Downloading: 100%
> Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
> Writing lock file
> Generating autoload files

**Comment by bm-services** [comment]
Bonjour,
et merci pour votre retour. Nous avons adapté le Readme pour qu'il soit moins ambigu et précise mieux les informations nécessaires, ce qui répond à vos 2 premiers points.

Pour le 3e point, cela concerne uniquement votre environnement de développement et ses accès vers l'extérieur (Packagist pour Composer), sur lequel nous ne pouvons rien faire.

Nous fermons donc la demande, n'hésitez pas à la rouvrir si vous souhaitez de plus amples informations.

Cordialement,
BM Services
