### ISSUE TITLE
Installation sans Composer

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [PayboxByVerifone/Magento2#4]
Bonjour,
Je ne trouve pas de documentation pour l'installation sans composer.. ?
Où est-ce que je dois uploader les fichiers svp ?

Ensuite je devrais faire 
php bin/magento module:enable paybox_epayment
.. ?

**Comment by ShapesGraphicStudio** [comment]
OK, j'ai créé les dossiers Paybox et Epayment : 
app/code/Paybox/Epayment
Et j'ai uploadé tout le contenu de Magento2-master.

Puis j'ai retrouvé le module dans le setup wizard de Magento où j'ai pu faire l'installation, tout me semble OK à priori.

**Comment by bm-services** [comment]
Bonjour,
désolé pour le délai de réponse, il vous faut effectivement déposer les sources directement dans "app/code" et recréer le Namespace du module, à savoir "Paybox/Epayment" et y déposer ensuite les fichiers.

Nous fermons donc la demande, n'hésitez pas à la rouvrir si vous souhaitez de plus amples informations.

Cordialement,
BM Services
