### ISSUE TITLE
Vérification des paramètres Paybox lors de l'utilisation d'un autre moyen de paiement

### ISSUE THREAD

**Issue by guillaume-netapsys** [PayboxByVerifone/Magento2#5]
Bonjour,

J'ai rencontré un bug lors de mes tests. Si l'on active Paybox dans le backend de M2 et que l'on active également un second moyen de paiement quelconque (Check Money Order pour mon test), et que l'on sélectionne ce dernier au moment du checkout, on récupère une erreur de type "Veuillez choisir une carte.".

Le problème vient de la vérification systématique des informations relatives à Paybox au moment de valider le moyen de paiement.
Le fichier event.xml fait référence à l'event "payment_method_assign_data" qui appelle l'observer "Paybox\Epayment\Observer\DataAssignObserver".

Cet observer récupère la méthode de paiement et appelle la méthode getHasCctypes() sur celle-ci. Sauf que si on parle d'un Check Money Order, getHasCctypes renvoie "null" et la condition `if($method->getHasCctypes() === false){` n'est pas remplie, la fonction continue et vérifie le "cctype", qui n'existe pas.

Il faudrait donc vérifier qu'il s'agisse bien d'une méthode de paiement Paybox avant d'utiliser `getHasCctypes`.

Pour ma part, j'ai rewrite la méthode execute de "Paybox\Epayment\Observer\DataAssignObserver" pour faire une première vérification sur un résultat "null" avant toute chose.

Bien cordialement.

**Comment by tarnagas** [comment]
Same issue. On Magento ~> 2.1.

**Comment by bm-services** [comment]
Bonjour,
et merci pour votre retour. Ce comportement a été corrigé dans la version 1.0.7 de l'extension.

- - - - - - - - - - - - - -

Hi,
this behavior has been fixed in the 1.0.7 release

**Comment by bm-services** [comment]
Nous fermons le ticket, merci de le ré-ouvrir ou de créer un nouveau ticket si la correction n'apporte pas satisfaction.
