### ISSUE TITLE
Mail envoyé après le paiement

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [PayboxByVerifone/Magento2#6]
Bonjour,
Je suis sur Magento 2.1.7 avec PayBox 1.0.5, et le mail envoyé après le paiement est le mail de confirmation d'order et non le mail de nouvelle facture, donc le mail de confirmation d'order est envoyé 2 fois.
J'ai pourtant bien paramétré les mails transactionnels dans l'administration.

En commentant les lignes : 
```
$orderSender = $this->_objectManager->get('Magento\Sales\Model\Order\Email\Sender\OrderSender');
$orderSender->send($order);
```
dans app/code/Paybox/Epayment/Model/Payment/AbstractPayment.php
comme on me l'a conseillé ici : 
[https://community.magento.com/t5/Technical-Issues/Magento-2-order-and-invoice-emails/m-p/68775#M2480](https://community.magento.com/t5/Technical-Issues/Magento-2-order-and-invoice-emails/m-p/68775#M2480)
je n'ai plus le doublon, mais je n'ai toujours pas le mail de facture.

Donc il semble qu'il faille corriger ces 2 lignes pour envoyer la facture.. ?

Une idée pour régler ça svp ?

**Comment by ShapesGraphicStudio** [comment]
J'ai essayé de changer les lignes : 
```
$orderSender = $this->_objectManager->get('Magento\Sales\Model\Order\Email\Sender\OrderSender');
$orderSender->send($order);
```
par : 
```
$invoiceSender = $this->_objectManager->get('Magento\Sales\Model\Order\Email\Sender\InvoiceSender');
$invoiceSender->send($invoice);
```
Je ferai un retour ici même si ça fontionne mieux.

**Comment by ShapesGraphicStudio** [comment]
Ça ne m'a pas l'air de fonctionner, une idée svp ?

**Comment by ShapesGraphicStudio** [comment]
Bonjour,
Des nouvelles sur ce problème svp ?

**Comment by bm-services** [comment]
Bonjour,
merci pour votre retour et veuillez nous excuser pour le délai de mise en place de la correction.

La nouvelle version 1.0.7 corrige ce comportement ou la facture n'était pas envoyée par e-mail

Nous fermons le ticket, merci de le ré-ouvrir ou de créer un nouveau ticket si la correction n'apporte pas satisfaction.
