### ISSUE TITLE
Blank page on Payment redirect

### ISSUE THREAD

**Issue by congts** [PayboxByVerifone/Magento2#8]
Hello,
I'm trying to apply your module into our project. But I got a blank page after placing a new order on this URL (<domain>/fr/pbxep/payment/redirect/).
These are the errors in system.log:
` main.CRITICAL: Invalid template file: 'pbxep/info/default.phtml' in module: 'Paybox_Epayment' block's name: 'info_0' [] []`
`Warning: pack(): Type H: illegal hex digit  in /app/code/Paybox/Epayment/Model/Paybox.php on line 781`

I see that the file "pbxep/info/default.phtml" is in the adminhtml. How should I fix it?

Thank you in advance.

**Comment by AlexPernot** [comment]
The template problem seams to be in this file: https://github.com/PayboxByVerifone/Magento2/blob/0f8f7f52ab192c5279cdf37febb166484a2af661/Block/Info.php#L62

The block is expecting to be instantiated from the Magento backend, so this line crashes when it's called from the frontend area.

I have the same problem when trying to send an order mail. I'll try to hack something, but an official fix would be better.

@congts For your pack() problem, you should set your HMAC key in the backend.

**Comment by bm-services** [comment]
Thank you for your interest in this module and your report. Despite our tests we never had this error before. The source of the problem is that this template should only be called on Back Office (it's the template of payment information on order page), that seems to be not always the case.

We are working on a new version that will fix this problem, the release should be available in the next 10 days.

**Comment by bm-services** [comment]
@congts Hi, would it be possible to know which version of Magento you we using? We are trying to reproduce and fix your problem. Thanks!

**Comment by bm-services** [comment]
Hi,
instead of using a template in base folder for all uses BO / FO, we added a new template in frontend folder with less information.

Let us know if you still have trouble with this solution.

Regards,
BM Services

**Comment by AlexPernot** [comment]
It works perfectly now, thanks!

**Comment by congts** [comment]
It works. Thanks for your support. I close this ticket.

**Comment by Quent6457** [comment]
hi i have always the trouble of blank page redirect when i placed a order how fix it ? i'm in magento 2.2.6

**Comment by LSERRE** [comment]
Same issue here in 2.2.6

**Comment by eInyzant** [comment]
same for me in 2.2.6 is there any fix yet ?

**Comment by Quent6457** [comment]
Yes for me ! verify you  Verifone e-commerce Back Office password and your HMAC password or regenerate HMAC key on backoffice from Paybox account.

**Comment by eInyzant** [comment]
hmm I did not change the default hmac. I thought it worked with the test settings that came with the extension.
Now I just saved the configuration without changing anything and it seems to work. Maybe an issue with the default configuration config.xml until it is saved in database ?
@Quent6457 thank you for your answer
